build:
	mkdir -p ./target
	gcc -o ./target/AnalogOutputAndCounterRead AnalogOutputAndCounterRead.c -lccnt -lcaio
run:
	mkdir -p ./target
	gcc -o ./target/AnalogOutputAndCounterRead AnalogOutputAndCounterRead.c -lccnt -lcaio
	./target/AnalogOutputAndCounterRead
clean:
	rm -rf ./target
